### ISSUE TITLE
List of models in result exporter is not refreshing

### ISSUE THREAD

**Issue by janosborst** [ChristianKahmann/ilcm_Shiny#93]
![image](https://user-images.githubusercontent.com/15791797/162229964-ca2abc96-06e8-472c-a538-b514faeeaf94.png)

When clicking on results sets, I cannot see latest models until I manually restart.

**Comment by JaBorst** [comment]
Same for Precalculated model in the task scheduler:
![image](https://user-images.githubusercontent.com/15791797/162230662-d800940f-0380-4ece-ad25-81150a53242f.png)
